services:
  gameoflife:
    image: game-of-life-api
    build:
      context: .
      dockerfile: GameOfLife.Api/Dockerfile
    ports:
      - "7097:80"
      - "7098:443"
    depends_on:
      - game-of-life-db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=game_of_life;Username=conway;Password=g@m30fl1f3
      - ASPNETCORE_ENVIRONMENT=Development

  postgres:
    image: postgres:16
    container_name: game-of-life-db
    restart: always
    environment:
      POSTGRES_USER: conway
      POSTGRES_PASSWORD: g@m30fl1f3
      POSTGRES_DB: game_of_life
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

